site_name: EvaML - Embodied Voice Assistant Markup Language - Documentation

theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo

    - scheme: slate
      primary: indigo
      accent: indigo


plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"


markdown_extensions:
  - pymdownx.inlinehilite

  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - footnotes
  - attr_list

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css



nav:
  - Home: index.md
  - EvaML: evaml.md
  # - Installation: installation.md
  - EvaML - Document Sections: evaml-doc-sections.md
  - Commands:
      - Overview: comandos/index.md
      - Controle de fluxo: comandos/controle.md
      - Entrada/Saída: comandos/io.md
      - Funções: comandos/funcoes.md
      - Variáveis e Tipos: comandos/variaveis.md
  - Real Scenarios:
      - EVA Robot: comandos/funcoes.md
      - FRED Robot: comandos/funcoes.md
  - Quick Reference:: referencia.md
  - FAQ: faq.md
  - About: sobre.md
